# -*- coding: utf-8 -*-
"""Hello.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/FredLongo/ColabTest/blob/main/Hello.ipynb
"""

def hello():
  print("Hello to you too!")